[ctf_questions]
enforceTypes = false
field.ctf_id = string
field.Number = number
field.Question = string
field.StartTime = number
field.EndTime = number
field.BasePoints = number
field.AdditionalBonusPoints = number
field.AdditionalBonusInstructions = string