[ctf_questions]
enforceTypes = false
field.ctf_id = string
field.Number = number
field.Question = string
field.StartTime = number
field.EndTime = number
field.BasePoints = number
field.AdditionalBonusPoints = number
field.AdditionalBonusInstructions = string
field.Subject = string
field.Category = string
field.ChallengeID = string
field.PrimarySourcetype = string
field.LearningObjective = string
field.ReferenceSPL = string
replicate = true

[ctf_answers]
enforceTypes = false
field.ctf_id = string
field.Answer = string
field.AnswerType = string
field.Number = string
replicate = true

[ctf_hints]
field.ctf_id = string
field.Hint = string
field.Number = string
field.HintNumber = string
field.HintCost = string
replicate = true
