[ctf_questions]
collection = ctf_questions
external_type = kvstore
fields_list = ctf_id, Number, Question, StartTime, EndTime, BasePoints, AdditionalBonusPoints, AdditionalBonusInstructions

[ctf_answers]
collection = ctf_answers
external_type = kvstore
fields_list = ctf_id, Number, Answer

[ctf_hints]
collection = ctf_hints
external_type = kvstore
fields_list = ctf_id, Number, Hint, HintNumber, HintCost

[whoisLookup]
external_cmd = whois_lookup.py ip whois
external_type = python
fields_list = ip, whois
python.version = python3

[currentscore]
batch_index_query = 0
case_sensitive_match = 1
filename = currentscore.csv
