[Generate Latest Scores and Ranks]
search = index=scoreboard ctf_id=* user!=admin \
| eval Team=coalesce(Team,user) \
| stats max(BasePointsAwarded) as BasePoints max(SpeedBonusAwarded) as BonusPoints max(AdditionalBonusAwarded) as AdditionalBonusPoints sum(Penalty) as Penalty by ctf_id Team Number \
| eval Score=coalesce(BasePoints,0)+coalesce(BonusPoints,0)+coalesce(AdditionalBonusPoints,0)-coalesce(Penalty,0) \
| stats sum(BasePoints) as BasePoints sum(BonusPoints) as BonusPoints sum(AdditionalBonusPoints) as AdditionalBonusPoints sum(Penalty) as Penalty sum(Score) as Score by ctf_id Team \
| sort 0 ctf_id - Score \
| streamstats count as Rank by ctf_id \
| outputlookup currentscore.csv

[Not Answered or Never Correctly Answered Questions]
search = index=scoreboard ctf_id=* user!=admin Result=* \
| stats values(user) as whoanswered values(Result) as Result by ctf_id Number \
| append [ | inputlookup ctf_questions | fields ctf_id Number ] \
| stats values(whoanswered) as whoanswered values(Result) as Result by ctf_id Number \
| eval NotAnswered=if(isnull(whoanswered),Number,null()) \
| eval NeverCorrect=if(isnull(mvfind(Result,".*Correct.*")),Number,null()) \
| where isnotnull(NotAnswered) OR isnotnull(NeverCorrect) \
| table ctf_id NotAnswered NeverCorrect

[Load staged questions]
search = | inputlookup ctf_questions_staged.csv \
| where isnotnull(ctf_id) AND ctf_id!="" \
| append [ | inputlookup ctf_questions ] \
| dedup ctf_id Number \
| outputlookup ctf_questions

[Load staged answers]
search = | inputlookup ctf_answers_staged.csv \
| where isnotnull(ctf_id) AND ctf_id!="" \
| append [ | inputlookup ctf_answers ] \
| dedup ctf_id Number \
| outputlookup ctf_answers

[Load staged hints]
search = | inputlookup ctf_hints_staged.csv \
| where isnotnull(ctf_id) AND ctf_id!="" \
| append [ | inputlookup ctf_hints ] \
| dedup ctf_id Number HintNumber \
| outputlookup ctf_hints

[Backup KV]
search = | inputlookup ctf_questions \
| eval collection="ctf_questions" \
| append [ | inputlookup ctf_answers | eval collection="ctf_answers" ] \
| append [ | inputlookup ctf_hints | eval collection="ctf_hints" ] \
| append [ | inputlookup ctf_hint_entitlements | eval collection="ctf_hint_entitlements" ] \
| append [ | inputlookup ctf_registrations | eval collection="ctf_registrations" ] \
| append [ | inputlookup ctf_events | eval collection="ctf_events" ] \
| append [ | inputlookup ctf_badges | eval collection="ctf_badges" ] \
| append [ | inputlookup ctf_badge_entitlements | eval collection="ctf_badge_entitlements" ] \
| append [ | inputlookup ctf_stealth | eval collection="ctf_stealth" ] \
| append [ | inputlookup ctf_eulas | eval collection="ctf_eulas" ] \
| append [ | inputlookup ctf_eulas_accepted | eval collection="ctf_eulas_accepted" ] \
| collect index="scoreboard_admin_kv"
